export const contactList = [
	{
		id: 1,
		name: "Robert Downey",
		profilePic: "../profile/tony.jpg",
		LastMessageTime: "2023-01-20T13:12:23.599Z",
		unseenMessages: "2",
		messagesList: [
			{
				id: 1,
				messageType: "TEXT",
				text: "Hey Man 😎",
				senderID: 0,
				addedOn: "12:00 PM",
			},
			{
				id: 2,
				messageType: "TEXT",
				text: "Hey, What's up?",
				senderID: 1,
				addedOn: "12:01 PM",
			},
			{
				id: 3,
				messageType: "TEXT",
				text: "All Good, What about you?",
				senderID: 0,
				addedOn: "12:00 PM",
			},
			{
				id: 4,
				messageType: "TEXT",
				text: "I'm good as well",
				senderID: 1,
				addedOn: "12:00 PM",
			},
			{
				id: 5,
				messageType: "TEXT",
				text: "See you later",
				senderID: 0,
				addedOn: "12:23 PM",
			},
			{
				id: 6,
				messageType: "TEXT",
				text: "Bye",
				senderID: 0,
				addedOn: "12:23 PM",
			}
		],
	},
	{
		id: 2,
		name: "Mark Ruffalo",
		profilePic: `../profile/bruce.jpg`,
		LastMessageTime: "2023-01-20T13:12:11.589Z",
		unseenMessages: "2",
		messagesList: [
			{
				id: 1,
				messageType: "TEXT",
				text: "Hey Sam😀!",
				senderID: 0,
				addedOn: "12:00 PM",
			},
			{
				id: 2,
				messageType: "TEXT",
				text: "How’s it going?",
				senderID: 1,
				addedOn: "12:00 PM",
			},
			{
				id: 3,
				messageType: "TEXT",
				text: "Yeah, good. Working a lot. And you?",
				senderID: 0,
				addedOn: "12:01 PM",
			},
			{
				id: 4,
				messageType: "TEXT",
				text: " Yeah, same here. I’m working on a new project.",
				senderID: 1,
				addedOn: "12:01 PM",
			},
			{
				id: 5,
				messageType: "TEXT",
				text: "Good for you! 🙂",
				senderID: 0,
				addedOn: "12:02 PM",
			},
			{
				id: 6,
				messageType: "TEXT",
				text: "Bye!",
				senderID: 1,
				addedOn: "12:02 PM",
			},
			{
				id: 7,
				messageType: "TEXT",
				text: "Bye!",
				senderID: 0,
				addedOn: "12:11 PM",
			},
			{
				id: 8,
				messageType: "TEXT",
				text: "Hello!",
				senderID: 0,
				addedOn: "12:11 PM",
			}
		],
	},
	{
		id: 3,
		name: "Chris Hemsworth",
		profilePic: "../profile/thor.jpeg",
		LastMessageTime: "2023-01-20T13:12:11.599Z",
		unseenMessages: "3",
		messagesList: [
			{
				id: 1,
				messageType: "TEXT",
				text: "Hey Sachin",
				senderID: 0,
				addedOn: "12:12 PM",
			},
			{
				id: 2,
				messageType: "TEXT",
				text: "Hey, What's up Chris?",
				senderID: 1,
				addedOn: "12:13 PM",
			},
			{
				id: 3,
				messageType: "TEXT",
				text: "What have you been up to😀?",
				senderID: 0,
				addedOn: "12:13 PM",
			},
			{
				id: 4,
				messageType: "TEXT",
				text: "Working a lot.🥴",
				senderID: 1,
				addedOn: "12:14 PM",
			},
			{
				id: 5,
				messageType: "TEXT",
				text: "That sounds hard.",
				senderID: 0,
				addedOn: "12:14 PM",
			},
			{
				id: 6,
				messageType: "TEXT",
				text: "then, when are you free?",
				senderID: 0,
				addedOn: "12:11 PM",
			},
			{
				id: 7,
				messageType: "TEXT",
				text: "Let me know when you are free",
				senderID: 0,
				addedOn: "12:11 PM",
			},
		],
	},
	{
		id: 4,
		name: "Scarlett Johansson",
		profilePic: "../profile/scarlett.jpg",
		LastMessageTime: "2023-01-20T13:12:08.599Z",
		unseenMessages: "1",
		messagesList: [
			{
				id: 1,
				messageType: "TEXT",
				text: "Hey Scarlett",
				senderID: 1,
				addedOn: "12:17 PM",
			},
			{
				id: 2,
				messageType: "TEXT",
				text: "Hey, What's up😃?",
				senderID: 0,
				addedOn: "12:17 PM",
			},
			{
				id: 3,
				messageType: "TEXT",
				text: "All Good, What about you?",
				senderID: 1,
				addedOn: "12:18 PM",
			},
			{
				id: 4,
				messageType: "TEXT",
				text: "I'm good as well",
				senderID: 0,
				addedOn: "12:18 PM",
			},
			{
				id: 5,
				messageType: "TEXT",
				text: "Great 😁",
				senderID: 1,
				addedOn: "12:18 PM",
			},
			{
				id: 6,
				messageType: "TEXT",
				text: "Have you seen the new movie🤩?",
				senderID: 0,
				addedOn: "12:19 PM",
			},
			{
				id: 7,
				messageType: "TEXT",
				text: "No?",
				senderID: 1,
				addedOn: "12:20 PM",
			},
			{
				id: 8,
				messageType: "TEXT",
				text: "Are you free this weekend?",
				senderID: 0,
				addedOn: "12:20 PM",
			},
			{
				id: 9,
				messageType: "TEXT",
				text: "I think so, why?",
				senderID: 1,
				addedOn: "12:20 PM",
			},
			{
				id: 10,
				messageType: "TEXT",
				text: "Want to see a movie🤩?",
				senderID: 0,
				addedOn: "12:20 PM",
			},
			{
				id: 11,
				messageType: "TEXT",
				text: "Sure😊",
				senderID: 1,
				addedOn: "12:20 PM",
			},
			{
				id: 12,
				messageType: "TEXT",
				text: "ok, let's meet at 7:00 PM at the theatre",
				senderID: 0,
				addedOn: "12:08 PM",
			},
		],
	},
	{
		id: 5,
		name: "Peter Parker",
		profilePic: "../profile/tom.jpg",
		LastMessageTime: "2023-01-20T13:12:03.599Z",
		unseenMessages: "",
		messagesList: [
			{
				id: 1,
				messageType: "TEXT",
				text: "Hey Robert",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 2,
				messageType: "TEXT",
				text: "Hey, What's up😃?",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 3,
				messageType: "TEXT",
				text: "All Good, What about you?",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 4,
				messageType: "TEXT",
				text: "I'm good as well",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 5,
				messageType: "TEXT",
				text: "Great 😁",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 6,
				messageType: "TEXT",
				text: "Have you seen the new movie🤩?",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 7,
				messageType: "TEXT",
				text: "No?",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 8,
				messageType: "TEXT",
				text: "Are you free this weekend?",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 9,
				messageType: "TEXT",
				text: "I think so, why?",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 10,
				messageType: "TEXT",
				text: "Want to see a movie🤩?",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 11,
				messageType: "TEXT",
				text: "Sure😊",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 12,
				messageType: "TEXT",
				text: "ok, let's meet at 7:00 PM at the theatre",
				senderID: 1,
				addedOn: "12:03 PM",
			},
		],
	},
	{
		id: 6,
		name: "Chris Evans",
		profilePic: "../profile/chris.jpg",
		LastMessageTime: "2023-01-20T13:12:01.599Z",
		unseenMessages: "",
		messagesList: [
			{
				id: 1,
				messageType: "TEXT",
				text: "Hey Chris",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 2,
				messageType: "TEXT",
				text: "Hey, What's up😃?",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 3,
				messageType: "TEXT",
				text: "All Good, What about you?",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 4,
				messageType: "TEXT",
				text: "I'm good as well",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 5,
				messageType: "TEXT",
				text: "Great 😁",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 6,
				messageType: "TEXT",
				text: "what are you doing this weekend?",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 7,
				messageType: "TEXT",
				text: "Nothing much, why?",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 8,
				messageType: "TEXT",
				text: "Just wanted to know if you are free this weekend?",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 9,
				messageType: "TEXT",
				text: "Ok",
				senderID: 0,
				addedOn: "12:28 PM",
			},
			{
				id: 10,
				messageType: "TEXT",
				text: "okay, bye",
				senderID: 1,
				addedOn: "12:01 PM",
			},
		],
	},
	{
		id: 7,
		name: "Paul Walker",
		profilePic: "../profile/paul.jpg",
		LastMessageTime: "2023-01-20T13:12:01.499Z",
		unseenMessages: "",
		messagesList: [
			{
				id: 1,
				messageType: "TEXT",
				text: "Hey Paul",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 2,
				messageType: "TEXT",
				text: "Hey, What's up😃?",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 3,
				messageType: "TEXT",
				text: "All Good, What about you?",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 4,
				messageType: "TEXT",
				text: "I'm good as well",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 5,
				messageType: "TEXT",
				text: "So, where are you from?",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 6,
				messageType: "TEXT",
				text: "I'm from California",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 7,
				messageType: "TEXT",
				text: "Oh, I'm from New York",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 8,
				messageType: "TEXT",
				text: "Oh, that's cool",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 9,
				messageType: "TEXT",
				text: "So, what do you do?",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 10,
				messageType: "TEXT",
				text: "I'm a software developer",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 11,
				messageType: "TEXT",
				text: "Oh, that's cool",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 12,
				messageType: "TEXT",
				text: "Yeah, I love my job",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 13,
				messageType: "TEXT",
				text: "What do you do?",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 14,
				messageType: "TEXT",
				text: "I'm a doctor",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 15,
				messageType: "TEXT",
				text: "Oh, that's cool",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 16,
				messageType: "TEXT",
				text: "Yeah, I love my job",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 17,
				messageType: "TEXT",
				text: "So, what are you doing this weekend?",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 18,
				messageType: "TEXT",
				text: "Nothing much, why?",
				senderID: 1,
				addedOn: "12:22 PM",
			},
			{
				id: 19,
				messageType: "TEXT",
				text: "Just wanted to know if you are free this weekend?",
				senderID: 0,
				addedOn: "12:22 PM",
			},
			{
				id: 20,
				messageType: "TEXT",
				text: "Yeah, I'm free",
				senderID: 1,
				addedOn: "12:22 PM",
			},
		]
	},
];